MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
    OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
    TWO_BRANCH: False
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    MLP_HEAD_DIM: 2048
    NUM_CLASSES: 500
    RECONST_LOSS: "smoothL1"
    RECONST_W: 5.
  CLS_AGNOSTIC_BBOX_REG: True
DATASETS:
  TRAIN: ("openimagesv4_challenge_train",)
  #TEST: ("coco_2014_minival",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
  NUM_WORKERS: 4
SOLVER:
  # for 4 GPUs
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (120000, 160000)
  MAX_ITER: 180000
  IMS_PER_BATCH: 8
  CHECKPOINT_PERIOD: 18000
